#!/usr/bin/env python3
"""Writes scripts/wordlists/uk-apostrophe.tsv from Helium314's main_uk.combined.

Every word with an apostrophe that the keyboard can hold (build-wordlist.py's is_word: letters,
apostrophes only between them) and whose source frequency is at least 9, all at 70. The source's
frequencies for these words are flat or shared by a family of forms, so they are not kept.

    scripts/uk-apostrophe-words.py main_uk.combined > scripts/wordlists/uk-apostrophe.tsv
"""
import importlib.util
import pathlib
import re
import sys

HEADER = """\
# Every Ukrainian word with an apostrophe in Helium314's list (wordlists_experimental/main_uk.combined,
# CC BY 4.0, https://codeberg.org/Helium314/aosp-dictionaries), all at 70: just above uk.txt's
# floor of 69, so each is known, completed and restored ("розвязок" to "розв'язок") but never
# outranks an everyday word. The source's own frequencies for these words are flat (almost all
# 10) or shared across a family of forms, so they are not used; the everyday ones have their own
# tiers in uk-everyday.tsv. Generated by scripts/uk-apostrophe-words.py, never hand-edited.
# Merged into uk.txt by
#   scripts/build-wordlist.py app/src/main/assets/dictionaries/uk.txt app/src/main/assets/dictionaries/uk.txt --floor 0 \\
#     --boost scripts/wordlists/uk-everyday.tsv --boost scripts/wordlists/uk-apostrophe.tsv
"""

SOURCE_LINE = re.compile(r" word=([^,]*),f=(\d+)")
MIN_SOURCE_FREQUENCY = 9
FREQUENCY = 70


def main() -> int:
    spec = importlib.util.spec_from_file_location("build_wordlist", pathlib.Path(__file__).with_name("build-wordlist.py"))
    builder = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(builder)
    words = set()
    with open(sys.argv[1], encoding="utf-8") as source:
        for line in source:
            match = SOURCE_LINE.match(line)
            if not match or int(match.group(2)) < MIN_SOURCE_FREQUENCY:
                continue
            word = builder.normalize(match.group(1))
            if "'" in word and builder.is_word(word):
                words.add(word)
    sys.stdout.write(HEADER)
    for word in sorted(words):
        sys.stdout.write(f"{word}\t{FREQUENCY}\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
